# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RadioX' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RadioX

  target 'RadioXTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RadioXUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'FaveButton', '~> 2.0.3'

end
